{{- if .Values.integrationTests.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
  name: {{ .Values.integrationTests.service.name }}
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
      - statefulsets
    verbs:
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/exec
      - services
    verbs:
      - get
      - list
      - patch
      - update
      - watch
{{- end }}