{{- if .Values.integrationTests.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
  name: {{ .Values.integrationTests.service.name }}
{{- end }}