{{- if .Values.backupDaemon.install }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
  name: {{ template "zookeeper.name" . }}-backup-daemon
subjects:
- kind: ServiceAccount
  name: {{ template "zookeeper.name" . }}-backup-daemon
roleRef:
  kind: Role
  name: {{ template "zookeeper.name" . }}-backup-daemon
  apiGroup: rbac.authorization.k8s.io
{{- end }}