{{- if .Values.backupDaemon.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
  name: {{ template "zookeeper.name" . }}-backup-daemon-secret
  {{- if eq (include "vault.enabled" .) "true" }}
  annotations:
    vault.qubership.org/refresh-credentials: {{ default "false" .Values.vaultSecretManagement.refreshCredentials | quote }}
  {{- end }}
type: Opaque
stringData:
  username: {{ .Values.global.secrets.backupDaemon.username | default "" | quote }}
  {{- if eq (include "vault.enabled" .) "false" }}
  password: {{ .Values.global.secrets.backupDaemon.password | default "" | quote }}
  zookeeper-admin-username: {{ coalesce (include "zookeeper.adminUsername" .) .Values.backupDaemon.zooKeeperAdminUsername | default "" | quote }}
  zookeeper-admin-password: {{ coalesce (include "zookeeper.adminPassword" .) .Values.backupDaemon.zooKeeperAdminPassword | default "" | quote }}
  {{- end }}
{{- end }}