{{- if (eq (include "monitoring.install" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
  name: {{ template "zookeeper.name" . }}-monitoring-secret
  {{- if eq (include "vault.enabled" .) "true" }}
  annotations:
    vault.qubership.org/refresh-credentials: {{ default "false" .Values.vaultSecretManagement.refreshCredentials | quote }}
  {{- end }}
type: Opaque
stringData:
  {{- if eq (include "vault.enabled" .) "false" }}
  zookeeper-client-username: {{ coalesce (include "zookeeper.clientUsername" .) .Values.monitoring.zooKeeperClientUsername | default "" | quote }}
  zookeeper-client-password: {{ coalesce (include "zookeeper.clientPassword" .) .Values.monitoring.zooKeeperClientPassword | default "" | quote }}
  {{- end }}
{{- end }}