{
 "title": "ZooKeeper Monitoring",
 "description": "ZooKeeper Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "influxdb" },
   {
    "name": "project",
    "label": "Project",
    "query": "SHOW TAG VALUES FROM zookeeper WITH KEY=project_name"
   },
   { "name": "side", "label": "DR Side", "query": "left,right" },
   {
    "name": "server",
    "label": "Server",
    "query": "SHOW TAG VALUES FROM zookeeper WITH KEY=server"
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,2m,5m,10m,30m,1h, 2h, 5h, 10h 1d"
   },
   {
    "name": "zk_pv_name",
    "label": "Volume",
    "query": "SHOW TAG VALUES FROM zookeeper_ext WITH KEY=~/zk_pv_name.*/ WHERE \"project_name\" =~ /^$project$/"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "singlestat",
   "description": "Status of ZooKeeper cluster",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zookeeper",
     "query": "SELECT max(\"status_code\") FROM \"zookeeper\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "graph",
   "description": "Status of ZooKeeper nodes",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "UP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zookeeper",
     "query": "SELECT min(\"alive_nodes\") FROM \"zookeeper\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "DOWN",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zookeeper",
     "query": "SELECT last(\"total_nodes\") - min(\"alive_nodes\") FROM \"zookeeper\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pod Memory Usage",
     "type": "graph",
     "description": "Memory usage by pod",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_pod_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "memory/usage",
       "query": "SELECT mean(\"value\") FROM \"memory/usage\" WHERE (\"namespace_name\" =~ /^$project$/ AND \"type\" = 'pod' AND \"pod_name\" =~ /$server(.*)/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_pod_name total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "memory/limit",
       "query": "SELECT mean(\"value\") FROM \"memory/limit\" WHERE (\"namespace_name\" =~ /^$project$/ AND \"type\" = 'pod' AND \"pod_name\" =~ /$server(.*)/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Pod CPU Usage",
     "type": "graph",
     "description": "CPU usage by pod",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "Millicores" }
     ],
     "targets": [
      {
       "alias": "$tag_pod_name",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu/usage_rate",
       "query": "SELECT mean(\"value\") FROM \"cpu/usage_rate\" WHERE (\"namespace_name\" =~ /^$project$/ AND \"type\" = 'pod' AND \"pod_name\" =~ /$server(.*)/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "$tag_pod_name total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "cpu/limit",
       "query": "SELECT mean(\"value\") FROM \"cpu/limit\" WHERE (\"namespace_name\" =~ /^$project$/ AND \"type\" = 'pod' AND \"pod_name\" =~ /$server(.*)/) AND $timeFilter GROUP BY time($__interval), \"pod_name\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Data Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of ZNodes",
     "type": "graph",
     "description": "The number of unique z-nodes on a ZooKeeper server has in its data tree",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper",
       "query": "SELECT mean(\"znode_count\") FROM \"zookeeper\" WHERE (\"project_name\" =~ /^$project$/ AND \"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Number of Ephemeral ZNodes",
     "type": "graph",
     "description": "The number of unique ephemeral z-nodes on a ZooKeeper server",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper",
       "query": "SELECT mean(\"ephemerals_count\") FROM \"zookeeper\" WHERE (\"project_name\" =~ /^$project$/ AND \"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Size of Data",
     "type": "graph",
     "description": "The size in bytes of the data tree for a ZooKeeper server",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper",
       "query": "SELECT last(\"approximate_data_size\") FROM \"zookeeper\" WHERE (\"project_name\" =~ /^$project$/ AND \"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(linear)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk usage in percent",
     "type": "graph",
     "description": "The data usage size in percent for a ZooKeeper server",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "t_disk",
       "query": "SELECT mean(\"used_percent\") FROM \"t_disk\" WHERE (\"path\" =~ /.*$zk_pv_name/) AND $timeFilter GROUP BY time($__interval), \"path\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk usage",
     "type": "graph",
     "description": "The data usage size in bytes for a ZooKeeper server",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "$tag_path",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "t_disk",
       "query": "SELECT mean(\"used\") FROM \"t_disk\" WHERE (\"path\" =~ /.*$zk_pv_name/) AND $timeFilter GROUP BY time($__interval), \"path\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Request Latency",
     "type": "graph",
     "description": "How long on average it takes for this ZooKeeper server to process a request in milliseconds. This is measured since the last restart of the ZooKeeper server",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper",
       "query": "SELECT max(\"average_latency\") FROM \"zookeeper\" WHERE (\"project_name\" =~ /^$project$/ AND \"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Minimum Request Latency",
     "type": "graph",
     "description": "The minimum time it took this ZooKeeper server to process a request in milliseconds. This is measured since the last restart of this ZooKeeper server",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper",
       "query": "SELECT max(\"min_latency\") FROM \"zookeeper\" WHERE (\"project_name\" =~ /^$project$/ AND \"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Maximum Request Latency",
     "type": "graph",
     "description": "The maximum time it took this ZooKeeper server to process a request in milliseconds. This is measured since the last restart of the ZooKeeper server",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper",
       "query": "SELECT max(\"max_latency\") FROM \"zookeeper\" WHERE (\"project_name\" =~ /^$project$/ AND \"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of Active Clients",
     "type": "graph",
     "description": "The number of active clients connected to a ZooKeeper server",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper",
       "query": "SELECT last(\"num_alive_connections\") FROM \"zookeeper\" WHERE (\"project_name\" =~ /^$project$/ AND \"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "ZooKeeper Packets Received",
     "type": "graph",
     "description": "How many ZooKeeper packets have been received by a ZooKeeper server",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper",
       "query": "SELECT mean(\"packets_received\") FROM \"zookeeper\" WHERE (\"project_name\" =~ /^$project$/ AND \"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "ZooKeeper Packets Sent",
     "type": "graph",
     "description": "How many ZooKeeper packets have been sent from a ZooKeeper server",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "$tag_server",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper",
       "query": "SELECT mean(\"packets_sent\") FROM \"zookeeper\" WHERE (\"project_name\" =~ /^$project$/ AND \"server\" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval), \"server\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Backup Daemon Status",
     "type": "singlestat",
     "description": "Shows the current activity status of the backup daemon. The activity status can be one of the following:\n* UP - There is at least one successful backup, and the latest backup is successful\n* WARNING - There are no successful backups, or the last backup failed\n* NOT ACTIVE - The backup is not satisfied\n* MISSING - The host of ZooKeeper Backup Daemon is not specified",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper_backup_metric",
       "query": "SELECT last(\"status\") FROM \"zookeeper_backup_metric\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Backup Status",
     "type": "singlestat",
     "description": "Shows the state of the last backup. The backup status can be one of the following:\n \n* SUCCESS - The latest backup is successful\n* FAILED - The latest backup failed\n* IN QUEUE - The latest backup is in queue\n* IN PROGRESS - The latest backup is in progress",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper_backup_metric",
       "query": "SELECT last(\"last_backup_status\") FROM \"zookeeper_backup_metric\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Time of Last Backup",
     "type": "singlestat",
     "description": "Shows the period of time when the last backup process was ended",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
     "format": "dateTimeFromNow",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper_backup_metric",
       "query": "SELECT last(\"last_backup_time\") FROM \"zookeeper_backup_metric\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backups Count",
     "type": "singlestat",
     "description": "Shows the amount of available backups",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper_backup_metric",
       "query": "SELECT last(\"backups_count\") FROM \"zookeeper_backup_metric\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Successful Backups Count",
     "type": "singlestat",
     "description": "Shows the amount of successful backups",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper_backup_metric",
       "query": "SELECT last(\"successful_backups_count\") FROM \"zookeeper_backup_metric\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Time of Last Successful Backup",
     "type": "singlestat",
     "description": "Shows the period of time when the last successful backup process was ended",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 20 },
     "format": "dateTimeFromNow",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper_backup_metric",
       "query": "SELECT last(\"last_successful_backup_time\") FROM \"zookeeper_backup_metric\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Storage Type",
     "type": "singlestat",
     "description": "Shows the backup storage type",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 20 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper_backup_metric",
       "query": "SELECT last(\"storage_type\") FROM \"zookeeper_backup_metric\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backup Last Version Size",
     "type": "graph",
     "description": "Shows the size of the last backup",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Backup Size",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper_backup_metric",
       "query": "SELECT last(\"last_backup_size\") FROM \"zookeeper_backup_metric\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Storage Size/Free Space",
     "type": "graph",
     "description": "Shows the space occupied by backups and the remaining amount of space. \nNot all storage supports total size, so \"Total Volume Space\" metrics can be zeroed",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "alias": "Used Volume Space",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper_backup_metric",
       "query": "SELECT (mean(\"storage_size\") - mean(\"storage_free_space\")) FROM \"zookeeper_backup_metric\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Total Volume Space",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper_backup_metric",
       "query": "SELECT mean(\"storage_size\") FROM \"zookeeper_backup_metric\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Time Spent on Backup",
     "type": "graph",
     "description": "Shows time spent on last backup",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Backup Time",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "zookeeper_backup_metric",
       "query": "SELECT mean(\"last_backup_spent_time\") FROM \"zookeeper_backup_metric\" WHERE (\"project_name\" =~ /^$project$/ AND \"host\" =~ /^$side/) AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "GC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC Collection Count",
     "type": "graph",
     "description": "This widget displays the number of garbage collections grouped by collection type. The statistics take into account two types of garbage collections: Copy - the garbage collector moves objects with links from eden space to survivor space and from survivor space to tenured space, \nMarkSweepCompact - the garbage collector works in tenured space, live objects are moved to the beginning, so garbage remains at the end of memory.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Collection Type - $tag_name: $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT non_negative_difference(max(\"count\")) FROM \"jvm_gc_collection_seconds\" WHERE (\"project_name\" =~ /^$project$/ AND \"url\" =~/$server/) AND $timeFilter GROUP BY time($__interval), \"url\",  \"name\"  fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "GC Collection Time",
     "type": "graph",
     "description": "This widget displays the time spent on garbage collections grouped by collection type. \nThe statistics take into account two types of garbage collections: Copy - the garbage collector moves objects with links from eden space to survivor space and from survivor space to tenured space, \nMarkSweepCompact - the garbage collector works in tenured space, live objects are moved to the beginning, so garbage remains at the end of memory.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "Collection Type - $tag_name: $tag_url",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "java_garbage_collector",
       "query": "SELECT non_negative_difference(max(\"sum\")) FROM \"jvm_gc_collection_seconds\" WHERE (\"project_name\" =~ /^$project$/ AND \"url\" =~/$server/) AND $timeFilter GROUP BY time($__interval), \"url\",  \"name\"  fill(null)",
       "select": [
        [
         { "params": [ "CollectionTime" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Heap Memory Usage",
     "type": "graph",
     "description": "This widget displays the general data on heap memory usage.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Used: $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_used_bytes\" WHERE (\"area\" = 'heap' AND \"project_name\" =~ /^$project$/ AND \"url\" =~/$server/) AND $timeFilter GROUP BY time($__interval), \"url\" fill(null)",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
       ]
      },
      {
       "alias": "Max: $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_max_bytes\" WHERE (\"area\" = 'heap' AND \"project_name\" =~ /^$project$/ AND \"url\" =~/$server/) AND $timeFilter GROUP BY time($__interval), \"url\" fill(null)",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
       ]
      },
      {
       "alias": "Committed: $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_committed_bytes\" WHERE (\"area\" = 'heap' AND \"project_name\" =~ /^$project$/ AND \"url\" =~/$server/) AND $timeFilter GROUP BY time($__interval), \"url\" fill(null)",
       "select": [
        [
         { "params": [ "HeapMemoryUsage.committed" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
       ]
      }
     ]
    },
    {
     "title": "JVM Memory Pool",
     "type": "graph",
     "description": "This widget displays the JVM Memory Pool consumption and limits.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Used_$tag_pool: $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_pool_used_bytes\" WHERE (\"project_name\" =~ /^$project$/ AND \"url\" =~/$server/) AND $timeFilter GROUP BY time($__interval), \"url\", \"pool\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Max_$tag_pool: $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_pool_max_bytes\" WHERE (\"project_name\" =~ /^$project$/ AND \"url\" =~/$server/) AND $timeFilter GROUP BY time($__interval), \"url\", \"pool\" fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Non-Heap Memory Usage",
     "type": "graph",
     "description": "This widget displays the general data on non heap memory usage.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "alias": "Used: $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_memory",
       "query": "SELECT mean(\"gauge\") FROM \"jvm_memory_used_bytes\" WHERE (\"area\" = 'nonheap' AND \"project_name\" =~ /^$project$/ AND \"url\" =~/$server/) AND $timeFilter GROUP BY time($__interval), \"url\" fill(null)",
       "select": [
        [
         { "params": [ "NonHeapMemoryUsage.used" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Count",
     "type": "graph",
     "description": "This widget displays the data about the thread count.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "alias": "Total Started: $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "query": "SELECT last(\"counter\") FROM \"jvm_threads_started_total\" WHERE (\"project_name\" =~ /^$project$/ AND \"url\" =~/$server/) AND $timeFilter GROUP BY time($__interval), \"url\" fill(null)",
       "select": [
        [
         { "params": [ "TotalStartedThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
       ]
      },
      {
       "alias": "Daemon: $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "query": "SELECT last(\"gauge\") FROM \"jvm_threads_daemon\" WHERE (\"project_name\" =~ /^$project$/ AND \"url\" =~/$server/) AND $timeFilter GROUP BY time($__interval), \"url\" fill(null)",
       "select": [
        [
         { "params": [ "DaemonThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
       ]
      },
      {
       "alias": "Peak: $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "query": "SELECT last(\"gauge\") FROM \"jvm_threads_peak\" WHERE (\"project_name\" =~ /^$project$/ AND \"url\" =~/$server/) AND $timeFilter GROUP BY time($__interval), \"url\" fill(null)",
       "select": [
        [
         { "params": [ "PeakThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
       ]
      },
      {
       "alias": "Total: $tag_url",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "java_threading",
       "query": "SELECT last(\"gauge\") FROM \"jvm_threads_current\" WHERE (\"project_name\" =~ /^$project$/ AND \"jolokia_agent_url\" =~/$server/) AND $timeFilter GROUP BY time($__interval), \"jolokia_agent_url\" fill(null)",
       "select": [
        [
         { "params": [ "ThreadCount" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}