# permissions for end users to edit zookeeperservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zookeeperservice-editor-role
rules:
- apiGroups:
  - qubership.org
  resources:
  - zookeeperservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - qubership.org
  resources:
  - zookeeperservices/status
  verbs:
  - get
