# permissions for end users to view zookeeperservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zookeeperservice-viewer-role
rules:
- apiGroups:
  - netcracker.com
  resources:
  - zookeeperservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - netcracker.com
  resources:
  - zookeeperservices/status
  verbs:
  - get
