= Security Hardening Guide

The document describes security hardening recommendations for ZooKeeper.

== Access Restriction

ZooKeeper should be secured against **unauthorized access**.

SASL authentication is supported as described in official documentation:
https://cwiki.apache.org/confluence/display/ZOOKEEPER/ZooKeeper+and+SASL

More features in official documentation:

* Authentication and authorization options https://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_authOptions
* Pluggable ZooKeeper authentication https://zookeeper.apache.org/doc/current/zookeeperProgrammers.html#sc_ZooKeeperPluggableAuthentication
* ZooKeeper access control using ACLs https://zookeeper.apache.org/doc/current/zookeeperProgrammers.html#sc_ZooKeeperAccessControl

=== Do not skip ACL checks

Skipping ACL checks results in a boost in throughput, but opens up full access to the data tree to everyone.
https://zookeeper.apache.org/doc/current/zookeeperAdmin.html#Unsafe+Options

== Logging

=== General Log

ZooKeeper uses **log4j** version 1.2 as its logging infrastructure. The ZooKeeper default __log4j.properties__ file resides in the __conf__ directory.

More details on general log in official documentation:
https://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_logging
https://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_advancedConfiguration

=== Audit Log

Security events and critical operations should be logged for audit purposes.

In currently supported by product ZooKeeper 3.5.0 no separate audit log 

ZooKeeper supports audit logs from version 3.5.3. By default audit logs are disabled.
To enable audit logs configure __audit.enable=true__ in __conf/zoo.cfg__. Audit logs are not logged on all the ZooKeeper servers, but logged only on the servers where client is connected.

More details on audit log in ticket:
https://issues.apache.org/jira/browse/ZOOKEEPER-1260

=== Things to Avoid

https://zookeeper.apache.org/doc/current/zookeeperAdmin.html#sc_commonProblems