{
 "title": "ZooKeeper Monitoring",
 "description": "ZooKeeper Prometheus Monitoring",
 "tags": [
  "Prometheus",
  "ZooKeeper"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(zookeeper_status_code, cluster)"
    }
   },
   {
    "name": "project",
    "label": "Project",
    "query": {
     "query": "label_values(zookeeper_status_code, namespace)"
    }
   },
   {
    "name": "server",
    "label": "Server",
    "query": {
     "query": "label_values(zookeeper_znode_count{project_name=\"$project\", cluster=\"$cluster\"},server)"
    }
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,2m,5m,10m,30m,1h, 2h, 5h, 10h 1d"
   },
   {
    "name": "zk_pod_names",
    "label": "ZooKeeper Pods",
    "query": {
     "query": "label_values(zookeeper_QuorumSize{namespace=\"$project\", cluster=\"$cluster\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "stat",
   "description": "Status of ZooKeeper cluster",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(zookeeper_status_code{project_name=\"$project\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Quorum Size",
   "type": "stat",
   "description": "Current count of ZooKeeper servers in quorum.",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(zookeeper_alive_nodes{project_name=\"$project\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Ready Pods",
   "type": "stat",
   "description": "Current count of ready pods.",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_ready{exported_namespace=\"$project\", exported_pod=~\"$zk_pod_names\", condition=\"true\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Leader Server",
   "type": "stat",
   "description": "Current leader server.",
   "gridPos": { "h": 5, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_CommitProcMaxCommitBatchSize{namespace=\"$project\",job=~\"$server*\",memberType=\"Leader\", cluster=\"$cluster\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "description": "Maximum current CPU usage (in percent) among all ZooKeeper servers.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * max(rate(container_cpu_usage_seconds_total{namespace=\"$project\", pod=~\"$zk_pod_names\",container=\"zookeeper\", cluster=\"$cluster\"}[5m])) / max(kube_pod_container_resource_limits_cpu_cores{exported_namespace=\"$project\",exported_pod=~\"$zk_pod_names\", cluster=\"$cluster\"})",
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "gauge",
   "description": "Maximum current JVM heap usage (in percent) among all ZooKeeper servers",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * max( jvm_memory_used_bytes{area=\"heap\",namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}) / max(jvm_memory_max_bytes{area=\"heap\",namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"})",
     "tags": [
      { "key": "project_name", "operator": "=~", "value": "/^$project$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Status Transitions",
   "type": "state-timeline",
   "description": "Transitions of ZooKeeper cluster statuses",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(zookeeper_status_code{namespace=\"$project\", cluster=\"$cluster\"})",
     "legendFormat": "Cluster State"
    }
   ]
  },
  {
   "title": "Pod Readiness Probe Transitions",
   "type": "state-timeline",
   "description": "Transitions of readiness probes for each ZooKeeper pod.",
   "gridPos": { "h": 5, "w": 13, "x": 7, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(kube_pod_status_ready{exported_namespace=\"$project\", exported_pod=~\"$zk_pod_names\", condition=\"true\", cluster=\"$cluster\"}) by (exported_pod)",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "Zookeeper Version",
   "type": "stat",
   "description": "Zookeeper Version",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "cluster": "$cluster",
     "expr": "zookeeper_version{namespace=\"$project\", version!=\"None\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "System Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Memory Usage",
   "type": "timeseries",
   "description": "Memory usage by pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_pod_name",
     "expr": "sum(container_memory_usage_bytes{namespace=\"$project\",pod=~\"$zk_pod_names\",container!=\"\",image!=\"\",cluster=\"$cluster\"}) by (pod)",
     "legendFormat": "Usage: {{pod}}"
    },
    {
     "alias": "$tag_pod_name total",
     "expr": "sum(kube_pod_container_resource_limits_memory_bytes{exported_namespace=\"$project\",exported_pod=~\"$zk_pod_names\", cluster=\"$cluster\"}) by (exported_pod)",
     "legendFormat": "Limit: {{exported_pod}}"
    }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "description": "CPU usage by pod",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_pod_name",
     "expr": "(sum(rate(container_cpu_usage_seconds_total{namespace=\"$project\", pod=~\"$zk_pod_names\",container!=\"\",image!=\"\",cluster=\"$cluster\"}[$__interval])) by (pod)) * 1000",
     "legendFormat": "Usage: {{pod}}"
    },
    {
     "alias": "$tag_pod_name total",
     "expr": "(sum(kube_pod_container_resource_limits_cpu_cores{exported_namespace=\"$project\",exported_pod=~\"$zk_pod_names\", cluster=\"$cluster\"}) by (exported_pod)) * 1000",
     "legendFormat": "Limit: {{exported_pod}}"
    }
   ]
  },
  {
   "title": "Data Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of ZNodes",
   "type": "timeseries",
   "description": "The number of unique z-nodes on a ZooKeeper server has in its data tree",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server",
     "expr": "sum(zookeeper_znode_count{server=~\"$server*\",project_name=\"$project\", cluster=\"$cluster\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Number of Ephemeral ZNodes",
   "type": "timeseries",
   "description": "The number of unique ephemeral z-nodes on a ZooKeeper server",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server",
     "expr": "sum(zookeeper_ephemerals_count{server=~\"$server*\",project_name=\"$project\", cluster=\"$cluster\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Size of Data",
   "type": "timeseries",
   "description": "The size in bytes of the data tree for a ZooKeeper server",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$tag_server",
     "expr": "sum(zookeeper_approximate_data_size{server=~\"$server*\",project_name=\"$project\", cluster=\"$cluster\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Disk usage in percent",
   "type": "timeseries",
   "description": "The data usage size in percent for a ZooKeeper server",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_path",
     "expr": "100* kubelet_volume_stats_used_bytes{namespace=\"$project\", cluster=\"$cluster\"} / kubelet_volume_stats_capacity_bytes{namespace=\"$project\", cluster=\"$cluster\"}",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "timeseries",
   "description": "The data usage size in bytes for a ZooKeeper server",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_path",
     "expr": "kubelet_volume_stats_used_bytes{namespace=\"$project\", cluster=\"$cluster\"}",
     "legendFormat": "Usage: {{persistentvolumeclaim}}"
    },
    {
     "alias": "$tag_path",
     "expr": "kubelet_volume_stats_capacity_bytes{namespace=\"$project\", cluster=\"$cluster\"}",
     "legendFormat": "Limit: {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "description": "How long on average it takes for this ZooKeeper server to process a request in milliseconds. This is measured since the last restart of the ZooKeeper server",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_server",
     "expr": "max(zookeeper_avg_latency{project_name=\"$project\",server=~\"$server*\", cluster=\"$cluster\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Minimum Request Latency",
   "type": "timeseries",
   "description": "The minimum time it took this ZooKeeper server to process a request in milliseconds. This is measured since the last restart of this ZooKeeper server",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_server",
     "expr": "max(zookeeper_min_latency{project_name=\"$project\",server=~\"$server*\", cluster=\"$cluster\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Maximum Request Latency",
   "type": "timeseries",
   "description": "The maximum time it took this ZooKeeper server to process a request in milliseconds. This is measured since the last restart of the ZooKeeper server",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$tag_server",
     "expr": "max(zookeeper_max_latency{project_name=\"$project\",server=~\"$server*\", cluster=\"$cluster\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Active Clients",
   "type": "timeseries",
   "description": "The number of active clients connected to a ZooKeeper server",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server",
     "expr": "max(zookeeper_num_alive_connections{project_name=\"$project\",server=~\"$server*\", cluster=\"$cluster\"}) by (server)",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Packets Received",
   "type": "timeseries",
   "description": "How many ZooKeeper packets have been received by a ZooKeeper server",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server",
     "expr": "rate(zookeeper_packets_received{project_name=\"$project\",server=~\"$server*\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "ZooKeeper Packets Sent",
   "type": "timeseries",
   "description": "How many ZooKeeper packets have been sent from a ZooKeeper server",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_server",
     "expr": "rate(zookeeper_packets_sent{project_name=\"$project\",server=~\"$server*\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{server}}"
    }
   ]
  },
  {
   "title": "GC Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "targets": [
    {}
   ]
  },
  {
   "title": "GC Collection Count",
   "type": "timeseries",
   "description": "This widget displays the number of garbage collections grouped by collection type. The statistics take into account two types of garbage collections: Copy - the garbage collector moves objects with links from eden space to survivor space and from survivor space to tenured space, \nMarkSweepCompact - the garbage collector works in tenured space, live objects are moved to the beginning, so garbage remains at the end of memory.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(idelta(jvm_gc_collection_seconds_count{namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}[5m])) by (job,gc)",
     "legendFormat": "Collection Type - {{gc}}: {{job}}"
    }
   ]
  },
  {
   "title": "GC Collection Time",
   "type": "timeseries",
   "description": "This widget displays the time spent on garbage collections grouped by collection type. \nThe statistics take into account two types of garbage collections: Copy - the garbage collector moves objects with links from eden space to survivor space and from survivor space to tenured space, \nMarkSweepCompact - the garbage collector works in tenured space, live objects are moved to the beginning, so garbage remains at the end of memory.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(idelta(jvm_gc_collection_seconds_sum{namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}[5m])) by (job,gc)",
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "legendFormat": "Collection Type - {{gc}}: {{job}}",
     "measurement": "java_garbage_collector",
     "select": [
      [
       { "params": [ "CollectionTime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "timeseries",
   "description": "This widget displays the general data on heap memory usage.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\",namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Usage: {{job}}",
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"heap\",namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Limit: {{job}}",
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.max" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Heap Memory Usage In Percent",
   "type": "timeseries",
   "description": "This widget displays the general data on heap memory usage in percent (%).",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * jvm_memory_used_bytes{area=\"heap\",namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"} / jvm_memory_max_bytes{area=\"heap\",namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Used: {{job}}",
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "HeapMemoryUsage.used" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "timeseries",
   "description": "JVM Memory Pool consumption and limits.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_pool_used_bytes{namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}",
     "legendFormat": "{{job}}: {{pool}}"
    },
    {
     "expr": "jvm_memory_pool_max_bytes{namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}",
     "legendFormat": "{{job}}: {{pool}} - max"
    }
   ]
  },
  {
   "title": "Non Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Non-Heap Memory Usage",
   "type": "timeseries",
   "description": "This widget displays the general data on non heap memory usage.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"nonheap\",namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Usage: {{job}}",
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.init" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "expr": "jvm_memory_committed_bytes{area=\"nonheap\",namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Commited: {{job}}",
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.init" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "expr": "jvm_memory_max_bytes{area=\"nonheap\",namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"} > 0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Max: {{job}}",
     "measurement": "java_memory",
     "select": [
      [
       { "params": [ "NonHeapMemoryUsage.init" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Threads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "description": "This widget displays the data about the thread count.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_threads_started_total{namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}) by (job)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Total Started: {{job}}",
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "TotalStartedThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Daemon: {{job}}",
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "DaemonThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "expr": "jvm_threads_peak{namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Peak: {{job}}",
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "PeakThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "expr": "jvm_threads_current{namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Thread Count: {{job}}",
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "ThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$project\",job=~\"$server*\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "legendFormat": "Thread Deadlocked: {{job}}",
     "measurement": "java_threading",
     "select": [
      [
       { "params": [ "ThreadCount" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "EC2_IPADDRESS", "operator": "=~", "value": "/^$IP$/" }
     ]
    }
   ]
  },
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 97 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backup Daemon Status",
   "type": "stat",
   "description": "Shows the current activity status of the backup daemon. The activity status can be one of the following:\n* UP - There is at least one successful backup, and the latest backup is successful\n* WARNING - There are no successful backups, or the last backup failed\n* NOT ACTIVE - The backup is not satisfied\n* MISSING - The host of ZooKeeper Backup Daemon is not specified",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_backup_metric_status{project_name=\"$project\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zookeeper_backup_metric"
    }
   ]
  },
  {
   "title": "Last Backup Status",
   "type": "stat",
   "description": "Shows the state of the last backup. The backup status can be one of the following:\n \n* SUCCESS - The latest backup is successful\n* FAILED - The latest backup failed\n* IN QUEUE - The latest backup is in queue\n* IN PROGRESS - The latest backup is in progress",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_backup_metric_last_backup_status{project_name=\"$project\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zookeeper_backup_metric"
    }
   ]
  },
  {
   "title": "Successful Backups Count",
   "type": "stat",
   "description": "Shows the amount of successful backups",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_backup_metric_successful_backups_count{project_name=\"$project\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zookeeper_backup_metric"
    }
   ]
  },
  {
   "title": "Backups Count",
   "type": "stat",
   "description": "Shows the amount of available backups",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_backup_metric_backups_count{project_name=\"$project\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zookeeper_backup_metric"
    }
   ]
  },
  {
   "title": "Backup Daemon Status Transitions",
   "type": "state-timeline",
   "description": "Transitions of ZooKeeper Backup Daemon statuses",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 105 },
   "targets": [
    {
     "expr": "zookeeper_backup_metric_status{project_name=\"$project\", cluster=\"$cluster\"}",
     "legendFormat": "Cluster State"
    }
   ]
  },
  {
   "title": "Time of Last Backup",
   "type": "stat",
   "description": "Shows the period of time when the last backup process was ended",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_backup_metric_last_backup_time{project_name=\"$project\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zookeeper_backup_metric"
    }
   ]
  },
  {
   "title": "Time of Last Successful Backup",
   "type": "stat",
   "description": "Shows the period of time when the last successful backup process was ended",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_backup_metric_last_successful_backup_time{project_name=\"$project\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zookeeper_backup_metric"
    }
   ]
  },
  {
   "title": "Storage Type",
   "type": "stat",
   "description": "Shows the backup storage type",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "zookeeper_backup_metric_storage_type{project_name=\"$project\", cluster=\"$cluster\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "zookeeper_backup_metric"
    }
   ]
  },
  {
   "title": "Backup Last Version Size",
   "type": "timeseries",
   "description": "Shows the size of the last backup",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "Backup Size",
     "expr": "zookeeper_backup_metric_last_backup_size{project_name=\"$project\", cluster=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Storage Size/Free Space",
   "type": "timeseries",
   "description": "Shows the space occupied by backups and the remaining amount of space. \nNot all storage supports total size, so \"Total Volume Space\" metrics can be zeroed",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Used Volume Space",
     "expr": "sum(zookeeper_backup_metric_storage_size{project_name=\"$project\", cluster=\"$cluster\"})",
     "legendFormat": "Storage Size"
    },
    {
     "expr": "sum(zookeeper_backup_metric_storage_size{project_name=\"$project\", cluster=\"$cluster\"}) - sum(zookeeper_backup_metric_storage_free_space{project_name=\"$project\", cluster=\"$cluster\"})",
     "legendFormat": "Used Volume Space"
    }
   ]
  },
  {
   "title": "Time Spent on Backup",
   "type": "timeseries",
   "description": "Shows time spent on last backup",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 119 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Backup Time",
     "expr": "sum(zookeeper_backup_metric_last_backup_spent_time{project_name=\"$project\", cluster=\"$cluster\"})"
    }
   ]
  }
 ]
}