{{- if .Values.integrationTests.install }}
kind: Secret
apiVersion: v1
metadata:
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
  name: {{ .Values.integrationTests.service.name }}-secret
stringData:
  prometheus-user: "{{ .Values.global.secrets.integrationTests.prometheus.user }}"
  prometheus-password: "{{ .Values.global.secrets.integrationTests.prometheus.password }}"
{{- end }}
