{{- if .Values.backupDaemon.install }}
{{- $s3Data := fromYaml (include "backupDaemon.s3Aliases" .) }}
{{- if $s3Data.items }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "zookeeper.name" . }}-backup-daemon-s3-aliases
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
    component: zookeeper-backup-daemon
    name: {{ template "zookeeper.name" . }}-backup-daemon
    app.kubernetes.io/name: {{ template "zookeeper.name" . }}-backup-daemon
    app.kubernetes.io/instance: {{ cat (printf "%s-backup-daemon" (include "zookeeper.name" .)) .Values.DELIMITER .Release.Namespace | nospace | trunc 63 }}
    app.kubernetes.io/technology: python
type: Opaque
stringData:
  s3_aliases.json: |
{{ include "backupDaemon.s3AliasesJson" . | indent 4 }}
{{- end }}
{{- end }}
