{{- if .Values.backupDaemon.install }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
  name: {{ template "zookeeper.name" . }}-backup-daemon
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/scale
    verbs:
      - create
      - get
      - list
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
{{- end }}