kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
  name: {{ template "zookeeper.name" . }}-service-operator
subjects:
- kind: ServiceAccount
  name: {{ template "zookeeper.name" . }}-service-operator
roleRef:
  kind: Role
  name: {{ template "zookeeper.name" . }}-service-operator
  apiGroup: rbac.authorization.k8s.io