{{- if .Values.backupDaemon.s3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
  name: {{ template "zookeeper.name" . }}-s3-secret
type: Opaque
stringData:
  s3-key-id: {{ .Values.backupDaemon.s3.keyId }}
  s3-key-secret: {{ .Values.backupDaemon.s3.keySecret }}
{{- end }}
