{{- if (and (eq (include "monitoring.install" .) "true") .Values.monitoring.installGrafanaDashboard) }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
    prometheus: zookeeper-tls-static-metrics-rules
    role: record-rules
  name: {{ template "zookeeper.name" . }}-tls-static-metrics-rules
spec:
  groups:
    - name: {{ .Release.Namespace }}-{{ .Release.Name }}
      rules:
        {{- include "global.tlsStaticMetric" (dict "namespace" .Release.Namespace "application" .Chart.Name "service" (include "zookeeper.name" .) "enabledSsl" (include "zookeeper-service.enableSsl" .) "secret" (include "zookeeper-service.sslSecretName" .) "certProvider" (include "services.certProvider" .) "certificate" (printf "%s-tls-certificate" (include "zookeeper.name" .))) | nindent 8 }}
        {{- if .Values.backupDaemon.install }}
        {{- include "global.tlsStaticMetric" (dict "namespace" .Release.Namespace "application" .Chart.Name "service" (printf "%s-backup-daemon" (include "zookeeper.name" .)) "enabledSsl" (include "backupDaemon.enableSsl" .) "secret" (include "backupDaemon.sslSecretName" .) "certProvider" (include "services.certProvider" .) "certificate" "zookeeper-backup-daemon-tls-certificate") | nindent 8 }}
        {{- end }}
{{- end }}
