{{- $secretName := include "zookeeper-service.sslSecretName" . }}
{{- $install := and .Values.global.tls.enabled .Values.zooKeeper.tls.enabled ( or .Values.global.tls.generateCerts.enabled (eq (include "zookeeper.certificatesSpecified" .) "true")) }}
{{- if and $install (eq (include "services.certProvider" .) "helm") (not (lookup "v1" "Secret" .Release.Namespace $secretName)) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
data:
{{- if not .Values.global.tls.generateCerts.enabled }}
  {{- if .Values.zooKeeper.tls.certificates.crt }}
  tls.crt: {{ .Values.zooKeeper.tls.certificates.crt | quote }}
  {{- end }}
  {{- if .Values.zooKeeper.tls.certificates.key }}
  tls.key: {{ .Values.zooKeeper.tls.certificates.key | quote  }}
  {{- end }}
  {{- if .Values.zooKeeper.tls.certificates.ca }}
  ca.crt: {{ .Values.zooKeeper.tls.certificates.ca | quote }}
  {{- end }}
{{- else }}
{{ ( include "zookeeper.generateCerts" . ) | indent 2 }}
{{ end }}
{{- end }}
