apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "zookeeper.defaultLabels" . | nindent 4 }}
  name: {{ template "zookeeper.name" . }}-secret
  {{- if eq (include "vault.enabled" .) "true" }}
  annotations:
    vault.qubership.org/refresh-credentials: {{ default "false" .Values.vaultSecretManagement.refreshCredentials | quote }}
  {{- end }}
type: Opaque
stringData:
  admin-username: {{ coalesce (include "zookeeper.adminUsername" .) .Values.zooKeeper.adminUsername | default "" | quote }}
  {{- if eq (include "vault.enabled" .) "false" }}
  admin-password: {{ coalesce (include "zookeeper.adminPassword" .) .Values.zooKeeper.adminPassword | default "" | quote }}
  {{- end }}
  client-username: {{ coalesce (include "zookeeper.clientUsername" .) .Values.zooKeeper.clientUsername | default "" | quote }}
  {{- if eq (include "vault.enabled" .) "false" }}
  client-password: {{ coalesce (include "zookeeper.clientPassword" .) .Values.zooKeeper.clientPassword | default "" | quote }}
  {{- end }}
  additional-users: {{ coalesce .Values.global.secrets.zooKeeper.additionalUsers .Values.zooKeeper.additionalUsers | default "" | quote }}