name: Branch Deleted
on: delete

env:
  TAG_NAME: ${{ github.event.ref }}

jobs:
  delete:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: qubership-zookeeper-integration-tests
            file: integration-tests/docker/Dockerfile
            context: integration-tests
          - name: qubership-zookeeper-operator
            file: operator/Dockerfile
            context: operator
          - name: qubership-zookeeper-transfer
            file: docker-transfer/Dockerfile
            context: ""
          - name: qubership-zookeeper-backup-daemon
            file: zookeeper-backup-daemon/docker/Dockerfile
            context: zookeeper-backup-daemon
          - name: qubership-zookeeper-monitoring
            file: zookeeper-monitoring/docker/Dockerfile
            context: zookeeper-monitoring
          - name: qubership-docker-zookeeper
            file: docker-zookeeper/docker/Dockerfile
            context: docker-zookeeper
    if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Tag
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV
      - name: Get package IDs for delete
        id: get-ids-for-delete
        uses: Netcracker/get-package-ids@v0.0.1
        with:
          component-name: ${{ matrix.component.name }}
          component-tag: ${{ env.TAG_NAME }}
          access-token: ${{secrets.GITHUB_TOKEN}}
      - uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ matrix.component.name }}
          package-type: 'container'
          package-version-ids: ${{ steps.get-ids-for-delete.outputs.ids-for-delete }}
        if: ${{ steps.get-ids-for-delete.outputs.ids-for-delete != '' }}
