---

name: Helm Charts Release
on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Release version'
        required: true
        type: string
permissions:
  contents: read

run-name: ${{ github.repository }} Release ${{ github.event.inputs.release }}
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  helm-charts-release:
    name: Helm Charts Release
    permissions:
      contents: write
      packages: write
    secrets: inherit
    uses: netcracker/qubership-workflow-hub/.github/workflows/re-infra-helm-release.yaml@8b1f50086b028c0ad22dafd33352e2166189b742 # v2.7.0
    with:
      release: ${{ inputs.release }}
      docker-config-file: ".qubership/docker-build-config.cfg"
      helm-charts-config-file: ".github/charts-values-update-config.yaml"
      max-parallel: 4
