name: Run Zookeeper Pipeline

permissions:
  contents: read
  packages: read
  actions: read

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  push:
    branches: [main]

jobs:
  Wait-for-images:
    runs-on: ubuntu-latest
    outputs:
      skip_tests: ${{ steps.check.outputs.skip_tests }}
    steps:
      - name: Check if dev_build.yml was triggered for this commit
        id: check
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            SHA="${{ github.event.pull_request.head.sha }}"
          else
            SHA="${{ github.sha }}"
          fi
          RUNS=$(gh run list --workflow dev_build.yml --repo ${{ github.repository }} --commit $SHA)
          SKIP_TESTS="false"
          if [ -z "$RUNS" ]; then
            SKIP_TESTS="true"
          fi
          echo SKIP_TESTS: $SKIP_TESTS
          echo "skip_tests=$SKIP_TESTS" >> $GITHUB_OUTPUT
      - name: Wait for dev_build.yml to complete
        if: steps.check.outputs.skip_tests == 'false'
        uses: netcracker/qubership-workflow-hub/actions/wait-for-workflow@3e428f45132119ce49d90f3770a45d4fe1d1078d  # v2.0.4
        id: wait
        with:
          workflow: dev_build.yml
          token: ${{ secrets.GITHUB_TOKEN }}
          poll-interval: 20

  Zookeeper-Pipeline:
    needs: Wait-for-images
    uses: Netcracker/qubership-test-pipelines/.github/workflows/zookeeper.yaml@905b88900dc8c14291eaeff4eddcf4d4f734aee1 #v1.9.0
    with:
      repository_name: ${{ github.repository }}
      service_branch: '${{ github.head_ref || github.ref_name }}'
      pipeline_branch: '905b88900dc8c14291eaeff4eddcf4d4f734aee1' #this value must match the value after '@' in 'uses'
      skip_tests: ${{ fromJSON(needs.Wait-for-images.outputs.skip_tests) }}
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
      AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}
