name: Run Nightly Zookeeper Pipeline

permissions:
  actions: write
  contents: read

on:
  schedule:
    - cron: '0 2 * * *'

jobs:
  Nightly-Zookeeper-Pipeline:
    uses: Netcracker/qubership-test-pipelines/.github/workflows/zookeeper.yaml@9fcb2de51b4d510b52ffca883515bdb388cbc16f #v1.14.0
    with:
      service_branch: '${{ github.head_ref || github.ref_name }}'
      pipeline_branch: '9fcb2de51b4d510b52ffca883515bdb388cbc16f' #this value must match the value after '@' in 'uses'
      runner_type: 'ubuntu-latest'
      scope: 'nightly'
      verify_timeout_minutes: 30
    secrets:
      AWS_S3_ACCESS_KEY_ID: ${{secrets.AWS_S3_ACCESS_KEY_ID}}
      AWS_S3_ACCESS_KEY_SECRET: ${{secrets.AWS_S3_ACCESS_KEY_SECRET}}
